config/routes.rb
Rails.application.routes.draw do

  root 'calendar#mainview'
  get 'parse' => 'calendar#parse'
  get 'drop' => 'calendar#drop'
  get 'event/:id', to: 'event#edit', as: 'event'
  post 'event/:id', to: 'event#edit'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  has_many :events
  has_and_belongs_to_many :departments
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_and_belongs_to_many :calendars
end

app/models/event.rb
class Event < ActiveRecord::Base
  include PgSearch
  multisearchable against: [:description, :summary, :location]
  has_and_belongs_to_many :tags
  belongs_to :calendar
  serialize :attach
  def time
    st = self.dtstart.strftime("%l:%M %p")
    se = self.dtend.strftime("%l:%M %p")
    if st == se
      "All Day"
    else
      st.to_s + '-' + se.to_s
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def mainview
    @title = "All Events"
    @active = {}
    @og = {}
    event = Event
    if !params[:search].blank?
      @active[:search] = params[:search]
      event = PgSearch.multisearch params[:search].to_s
      event = Event.where(id:event.map{|s| s.searchable_id})
    end
    if !params[:calendar].blank?
      @active[:calendar] = Calendar.find(params[:calendar])
      event = event.where(calendar:params[:calendar])
    end
    if !params[:tag].blank?
      @active[:tag] = Tag.find(params[:tag])
      event = event.joins(:tags).where(tags: {id: params[:tag]})
    end
    if !params[:date].blank?
      @active[:date] = Date.strptime(params[:date], "%m/%d/%Y")
      event = event.where("dtstart >= ?",@active[:date])
    end
    @ev = formatEvents event
    render template: "calendar/mainview1"
  end
  def parse
    parseCalendar
    render json: {a:1}
  end
  def drop
    Event.delete_all
    Calendar.delete_all
    Tag.delete_all
    render json: {a:1}
  end
  private
    def formatEvents(events)
      events = events.order("dtstart, dtend").group_by{|e| e.dtstart.to_date}
      events.each do |k, events_in_date|
        events[k] = events_in_date.group_by do |e|
          [e.dtstart.to_time, e.dtend.to_time]
        end
      end
      events
    end
    def parseCalendar
      require 'open-uri'
      require 'icalendar'
      urls = ["https://www.google.com/calendar/ical/e9runcnq4ejd2vvj4tpgb2qhro%40group.calendar.google.com/public/basic.ics",
            "https://www.google.com/calendar/ical/e4q9nvb58fg52qipvire5uvin4%40group.calendar.google.com/public/basic.ics"
            ]

      urls.each do |url|
        cal_str = ""
        open(URI.parse(url)) do |data|
          cal_str = cal_str + data.read
        end
        cals = Icalendar.parse(cal_str)
        cal = cals.first
        if Calendar.where(url:url).blank?
          Calendar.new(
            name:cal.custom_properties["x_wr_calname"].first.to_s,
            url:url
          ).save
        end

        calendar = Calendar.where(url:url).first
        cal.events.each do |e|
          saved_e = Event.where(uid:e.uid.to_s).first
          ev_desc = e.description.to_s
          splat = ev_desc.partition('TAGS:')
          ev_desc, tags = splat.first, splat.last.split(',')

          event_info = {
            summary: e.summary.to_s,
            description: ev_desc,
            location: e.location.to_s,
            dtstart: e.dtstart,
            dtend: e.dtend,
            created: e.created,
            last_modified: e.last_modified
          }

          #logger.debug "#{!saved_e.blank?}"
          #This irks me so much!
          if !saved_e.blank?
            if saved_e.last_modified < e.last_modified
              saved_e.update(event_info)
              saved_e.tags.each { |t| saved_e.tags.delete(t) }
              tags.each do |t|
                saved_e.tags << Tag.find_or_create_by(name: t)
              end
            end
          end
          next if !saved_e.blank?

          cal_event = calendar.events.new(uid: e.uid.to_s)
          cal_event.update(event_info)
          tags.each do |t|
            cal_event.tags << Tag.find_or_create_by(name: t)
          end
        end
      end
    end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def edit
    @ev = event
    @active = {}
    @title = "Event: #{@ev.summary}"
    if params[:event] and params[:event]['image']
      hash = Cloudinary::Uploader.upload(params[:event]['image'])
      if @ev.attach.blank?
        @ev.attach = []
      end
      @ev.attach.push(hash['public_id'])
    end
    img_i = false
    img_i = params[:img_index] unless params[:img_index].blank?
    if img_i and (img_i.to_i.to_s==img_i) and @ev.attach and img_i.to_i <= @ev.attach.length - 1
      @ev.attach.delete_at(img_i.to_i)
    end
    @ev.save
    @og = {title: @ev.summary}
    @og[:image] = @ev.attach.first if @ev.attach and !@ev.attach.first.blank?
  end
#<%= link_to @ev.calendar.name, calendar_path(@ev.calendar.name), style:"font-size:15px" %>
  private
    def event
      @ev ||= Event.find(params[:id])
      @ev or not_found
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/social_helper.rb
module SocialHelper
  def fb_tag(id)
    content_tag(:a,
        content_tag(:i, '', class: "fa fa-facebook") + " Share",
      class: "btn btn-xs btn-social btn-facebook",
      onclick:"postToFeed("+id.to_s+")")
  end
  def twitter_tag()
    %{<a class="btn btn-xs btn-social btn-twitter" >
      <i class="fa fa-twitter"></i> Tweet
    </a>}
    content_tag(:a,
        content_tag(:i, '', class:'fa fa-twitter') + "Tweet",
      class: "btn btn-xs btn-social btn-twitter")
  end
end

app/views/calendar/_mediaview.html.erb
<div id="accordion" class="panel-group">
  <% @ev.each do |date, datetime| %>
    <h2><%= date.to_date.strftime("%a %m/%d") %></h2>
    <% datetime.each do |datetime, events| %>
      <div class="media-list">
        <h6>
          <% if(datetime.first.strftime("%H:%M") == datetime.second.strftime("%H:%M")) %>
            --
          <% else %>
            <%= datetime.first.strftime("%I:%M %p")%> - <%=datetime.second.strftime("%I:%M %p") %>
          <% end %>
        </h6>
        <% events.each do |e| %>
          <li class="media">
            <% if e.attach %>
              <% #URI.unescape(e.attach.first.to_s) %>
              <a class="pull-left" href="#">
                <img style="width:150px;" src="<%= URI.unescape(e.attach.first.to_s) %>"></img>
              </a>
            <% end %>
            <div class="media-body">
              <div class="media-heading">
                <span style="display: block;font-size: 14px;line-height: 14px;">
                  <%= link_to e.calendar.name, calendar_path(e.calendar.name) %>
                </span>
                <h5 style="margin-top:5px"><%= e.summary %></h5>
              </div>
              <%= e.description %>
              <p>Tags:
                <% e.tags.each_with_index do |t, i| %>
                  <span class="label label-primary"><%= link_to t.name, tag_path(t.name), class:"label-tag" %></span>
                  <%= ',' if i+1 != e.tags.length %>
                <% end %>
              </p>
              <p><%= e.dtstart.to_time.strftime("%l:%M %p") %>-<%=e.dtend.to_time.strftime("%l:%M %p") %>; <%= e.location %></p>
              <%= fb_tag e.id %>
            </div>
          </li>
        <%end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/calendar/_rowview.html.erb
<div id="accordion" class="panel-group">
  <% @ev.each do |date, datetime| %>
    <h><%= date.to_date.strftime("%a %m/%d") %></h2>
    <% datetime.each do |datetime, events| %>
      <div class="">
        <div class="date-row row">
          <div class="col-xs-2">
            <p>
              <% if(datetime.first.strftime("%H:%M") == datetime.second.strftime("%H:%M")) %>
                --
              <% else %>
                <%= datetime.first.strftime("%I:%M %p")%> - <%=datetime.second.strftime("%I:%M %p") %>
              <% end %>
            </p>
          </div>
          <div class="col-xs-10">
            <% events.each do |e| %>
              <div class="col-md-6 col-sm-6">
                <div class="panel panel-primary">
                  <div class="event-heading panel-heading"
                        data-toggle="collapse"
                        data-parent="#accordion"
                        href="#event-<%= e.id %>">
                    <p class="event-title panel-title">
                      <%= link_to e.summary, event_path(e.id) %> <span class="calendar-title pull-right"><%= e.calendar.name %></span>
                    </p>
                  </div>
                  <div id="event-<%= e.id %>" class="panel-collapse collapse in">
                    <div class="panel-body">
                      <% #URI.unescape(e.attach.first.to_s) %>
                      <a class="pull-left" style="margin-right: 10px;" href="#">
                        <img style="max-width:150px;min-height:150px;" src="<%= URI.unescape(e.attach.first.to_s) %>"></img>
                      </a>
                      <p><%= link_to e.calendar.name, calendar_path(e.calendar.name) %></p>
                      <%= e.description %>
                      <p>Tags:
                        <% e.tags.each_with_index do |t, i| %>
                          <span class="label label-primary"><%= link_to t.name, tag_path(t.name), class:"label-tag" %></span>
                          <%= ',' if i+1 != e.tags.length %>
                        <% end %>
                      </p>
                      <p><%= e.dtstart.strftime("%l:%M %p") %>-<%=e.dtend.strftime("%l:%M %p") %>; <%= e.location %></p>
                      <%= fb_tag e.id %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/calendar/_tableview.html.erb
<style>
.collapsible-table td{
  border-top:none !important;
}
.unselectable {
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -o-user-select: none;
  user-select: none;
  cursor: default;
}
</style>
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <td class="col-md-2">#</td>
      <td class="col-md-5">Event</td>
      <td class="col-md-5">Calendar</td>
    </tr>
  </thead>
  <tbody>
    <% @ev.each do |date, datetime| %>
      <tr class="active">
        <td><b><%= date.to_date.strftime("%a %m/%d") %></b></td>
        <td></td>
        <td></td>
      </tr>
      <% datetime.each do |datetime, events| %>
        <% events.each do |e| %>
          <% event_data_slug = "event-data-" + e.id.to_s %>
          <tr class="unselectable"
              onclick="$('#event-data-<%= e.id %>').css('display', function () { return ($('#event-data-<%= e.id %>').css('display')=='table-row') ? 'none':'';})">
            <td>
              <% if(e.dtstart.to_time.strftime("%H:%M") == e.dtend.to_time.strftime("%H:%M")) %>
                --
              <% else %>
                <%= e.dtstart.to_time.strftime("%I:%M %p") %> - <%= e.dtend.to_time.strftime("%I:%M %p") %>
              <% end %>
            </td>
            <td>
              <%= link_to e.summary, event_path(e.id) %>
            </td>
            <td><%= link_to e.calendar.name, request.parameters.merge({calendar:1}) %></td>
          </tr>
          <tr id="event-data-<%= e.id %>" class="collapsible-table" style="display:none">
            <td class="col-md-2">
              <%= fb_tag e.id %><br>
              <%= twitter_tag %><br>
              <a type="button" class="btn btn-default btn-xs">
                <span class="glyphicon glyphicon-calendar"></span>|Copy to my Calendar
              </a><br>
              <% if !e.attach.blank? %>
                <a class="pull-left" style="margin-right: 10px;" href="#">
                  <img style="max-width:150px;min-height:150px;" src="<%= cloudinary_url(e.attach.first.to_s) %>"></img>
                </a>
              <% end %>
            </td>
            <td class="col-md-5">
              <% if not e.description.blank? %>
                <p><b>What:</b><%= e.description %></p>
              <% end %>
              <p>
                <b>When:</b><%= e.time %>
              </p>
              <% if not e.location.blank? %>
                <p><b>Where:</b><%= e.location %></p>
              <% end %>
            </td>
            <td class="col-md-5"><p>Tags:
              <% e.tags.each_with_index do |t, i| %>
                <span class="label label-primary"><%= link_to t.name, request.parameters.merge({tag:t.id}), class:"label-tag" %></span>
                <%= ',' if i+1 != e.tags.length %>
              <% end %>
            </p>
            </td></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/calendar/mainview.html.erb
<style>
  body{
    background-color:#F9F9F9;
  }
  #main {
    width: 100%;
    margin:auto;
  }
  .event-heading {
    cursor:pointer;
  }
  .label-tag{
    color:white;
  }
  .date-row{
    padding-bottom:10px;
  }
  .calendar-title{
  }
</style>
<h1><%= @title %></h1>
<div id="main">
  <% last_date = Date.civil(1996) %>
  <!--
    Logic Here is Wrong!
    If you have 3 items, it will row-ify the middle
    self.location=
  -->
  <div class="row">
    <div class="col-xs-6 col-md-8">
      <select id="select" class="form-control"
        onchange="self.location=this.options[this.selectedIndex].value">
        <option>Calendar</option>
        <% Calendar.all.each do |c| %>
          <option value="<%= calendar_path(c.name) %>"><%= c.name %></option>
        <% end %>
      </select>
    </div>
    <div class="col-xs-6 col-md-4">
      <select id="select" class="form-control"
        onchange="self.location=this.options[this.selectedIndex].value">
        <option>Tags</option>
        <% @tags.each do |t| %>
          <option value="<%= tag_path(t.name) %>"><%= t.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <%=  %>
  <% if true %>
  <%end%>
</div>
<script>
$('.collapse').collapse()
</script>

app/views/calendar/mainview1.html.erb
<%= render partial: "tableview", locals: { ev:@ev } %>

app/views/event/edit.html.erb
<h3><%= @ev.summary %>
  <%= link_to @ev.calendar.name, root_path(calendar:1) %>
</h3>
<div style="width:90%;margin:0 auto">
  <p>
    <span class="glyphicon glyphicon-time"></span><%= @ev.time %>
    <% if !@ev.location.blank? %>
      <span class="glyphicon glyphicon-map-marker"></span><%= @ev.location %>
    <% end %>
      <%= fb_tag @ev.id %>
      <%= twitter_tag %>
  </p>
  <p style="margin:0px;"><%= @ev.description %></p>
  <p>Tags:
    <% @ev.tags.each_with_index do |t, i| %>
      <span class="label label-primary"><%= link_to t.name, root_path({tag:t.id}), class:"label-tag" %></span>
      <%= ',' if i+1 != @ev.tags.length %>
    <% end %>
  </p>
  <div class="row">
    <% if !@ev.attach.blank? %>
    <% @ev.attach.each_with_index do |a, i| %>
      <div class="col-xs-6 col-md-4">
        <a href="<%= cloudinary_url(a, width:300) %>" data-type="image"
          data-toggle="lightbox" data-gallery="pubmats">
          <%= cl_image_tag(a, width: 300, alt: "Event PubMat", class:"pubmats img-responsive") %>
        </a>
          <a href="#" onclick="eventAttachmentDelete(<%=@ev.id%>,<%=i%>)"><span class="glyphicon glyphicon-remove"></span>Delete</a>
      </div>
    <% end %>
    <% end %>
  </div>

    <h5>Pubmat Form</h5>
    <%= form_for :event, html:{class:"form-inline"} do |event_form| %>
      <%= event_form.hidden_field(:image_cache) %>
      <div class="form-group">
        <label>File input</label>
        <%= event_form.file_field :image %>
        <p class="help-block">Add a PubMat here</p>
      </div>
      <%= event_form.submit "Upload", class:"btn btn-default" %>
    <% end %>
  </div>
<script>
function eventAttachmentDelete(id, i){
  var slug = "/event/" + id;
  $.post(slug, { img_index: i },
    function(){
      window.location.href=slug
  });
}
$(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
    event.preventDefault();
    $(this).ekkoLightbox();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta property="fb:app_id" content="1489219918029917" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:title" content="EventUP<%= (': ' + @og[:title].to_s) unless @og.blank? %>" />
  <meta property="og:image" content="<%= cloudinary_url @og[:image] %>" />
</head>
<body>
<!--<div class="fb-share-button" data-href="http://evup.herokuapp.com/"></div>
<div class="fb-login-button" data-show-faces="false" data-width="300"></div>
<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/"></div>
<p><a onclick='postToFeed(); return false;'>Post to Feed</a></p>-->
<div class="page-header">
  <h1><a href="/" style="color:inherit;text-decoration:none">EventUP</a></h1>
</div>
<div id="main">
  <% last_date = Date.civil(1996) %>
  <form id="event-constraint-form" action="/" method="get">
    <div class="row">
      <div class="col-sm-11">
        <div class="row">
          <div class="col-xs-6 col-md-8">
            <div class="input-group">
              <input name="search" type="text" id="event-constraint-search" class="form-control" value="<%= @active[:search] if !@active[:search].blank? %>">
                <span class="input-group-addon"><i id="event-constraint-search-button" class="glyphicon glyphicon-search" style="cursor:pointer"></i>
              </span>
            </div>
          </div>
          <div class="col-xs-6 col-md-4">
            <div class="input-group date">
              <input name="date" type="text" class="form-control" value="<%= @active[:date].strftime('%m/%d/%Y') if !@active[:date].blank? %>">
                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i>
              </span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6 col-md-8">
            <select id="select" name="calendar" class="form-control" onchange="submitEventConstraint()">
              <option value="">Calendar</option>
              <% Calendar.all.each do |c| %>
                <option value="<%= c.id %>" <%= 'selected="selected"' if @active[:calendar] == c %>><%= c.name %></option>
              <% end %>
            </select>
          </div>
          <div class="col-xs-6 col-md-4">
            <select id="select" name="tag" class="form-control" onchange="submitEventConstraint()">
              <option value="">Tag</option>
              <% Tag.all.each do |t| %>
                <option value="<%= t.id %>" <%= 'selected="selected"' if @active[:tag] == t %>><%= t.name %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
      <div class="col-sm-1">
        <a href="/"><small>Show All Events</small></a>
      </div>
    </div>
  </form>
  <%= yield %>
</div>

<script>
  $('.collapse').collapse();
  $('.input-group.date')
    .datepicker({todayHighlight: true})
    .on('changeDate', function(e){
      submitEventConstraint();
    });
  $('#event-constraint-search').keyup(function(e){
    if(e.keyCode==13){
      submitEventConstraint();
    }
  });
  $('#event-constraint-search-button').click(function(){
    submitEventConstraint();
  })
  function submitEventConstraint(){
    $('#event-constraint-form').submit();
  }
  window.fbAsyncInit = function() {
    FB.init({
      //appId : '1489220221363220',
      appId      : '1489219918029917',
      xfbml      : true,
      version    : 'v2.1'
    });
  };
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

  function postToFeed(i) {
    FB.ui(
    {
      method: 'share',
      href: 'http://evup.herokuapp.com/event/'+i,
    }, function(response){});
  }
</script>
</body>
</html>